// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DataRoot(): $CancellablePromise<string> {
    return $Call.ByID(2335082399);
}

export function Load(): $CancellablePromise<void> {
    return $Call.ByID(1847127963);
}

export function SetDataRoot(root: string): $CancellablePromise<void> {
    return $Call.ByID(2941178177, root);
}

export function SetEnabledOptional(slug: string, ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(3111766090, slug, ids);
}

export function SetExtraJVMArgs(slug: string, args: string[]): $CancellablePromise<void> {
    return $Call.ByID(2242105113, slug, args);
}

export function SetLastProfile(slug: string): $CancellablePromise<void> {
    return $Call.ByID(763022326, slug);
}

export function SetProfileRAM(slug: string, ramMB: number): $CancellablePromise<void> {
    return $Call.ByID(605338498, slug, ramMB);
}

export function Snapshot(): $CancellablePromise<$models.Config> {
    return $Call.ByID(2932004491).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
