// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    "version": number;
    "dataRoot": string;
    "lastProfile": string;
    "profiles": { [_ in string]?: ProfileConfig };

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("dataRoot" in $$source)) {
            this["dataRoot"] = "";
        }
        if (!("lastProfile" in $$source)) {
            this["lastProfile"] = "";
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField3_0($$parsedSource["profiles"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class ProfileConfig {
    "ramMB": number;
    "enabledOptional": string[];
    "extraJvmArgs": string[];

    /** Creates a new ProfileConfig instance. */
    constructor($$source: Partial<ProfileConfig> = {}) {
        if (!("ramMB" in $$source)) {
            this["ramMB"] = 0;
        }
        if (!("enabledOptional" in $$source)) {
            this["enabledOptional"] = [];
        }
        if (!("extraJvmArgs" in $$source)) {
            this["extraJvmArgs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileConfig {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enabledOptional" in $$parsedSource) {
            $$parsedSource["enabledOptional"] = $$createField1_0($$parsedSource["enabledOptional"]);
        }
        if ("extraJvmArgs" in $$parsedSource) {
            $$parsedSource["extraJvmArgs"] = $$createField2_0($$parsedSource["extraJvmArgs"]);
        }
        return new ProfileConfig($$parsedSource as Partial<ProfileConfig>);
    }
}

// Private type creation functions
const $$createType0 = ProfileConfig.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Array($Create.Any);
