// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ChangeDataRoot moves the data tree to newRoot and persists the choice. The
 * caller must Restart afterwards: the running services still hold the old layout.
 */
export function ChangeDataRoot(newRoot: string): $CancellablePromise<void> {
    return $Call.ByID(672173816, newRoot);
}

/**
 * CurrentDataRoot is where all game data lives right now.
 */
export function CurrentDataRoot(): $CancellablePromise<string> {
    return $Call.ByID(2388358213);
}

/**
 * OpenDataRoot opens the current data root in the OS file manager.
 */
export function OpenDataRoot(): $CancellablePromise<void> {
    return $Call.ByID(1381282728);
}

/**
 * OpenProfileDir opens the profile's folder in the OS file manager, creating it
 * first so there's something to show before the first launch.
 */
export function OpenProfileDir(slug: string): $CancellablePromise<void> {
    return $Call.ByID(3397125052, slug);
}

/**
 * PickDataRoot shows a directory chooser starting at the current root. Returns ""
 * when the user cancels.
 */
export function PickDataRoot(): $CancellablePromise<string> {
    return $Call.ByID(3106249105);
}

/**
 * ProfileDir is the on-disk directory holding a profile's game files.
 */
export function ProfileDir(slug: string): $CancellablePromise<string> {
    return $Call.ByID(1284986900, slug);
}

/**
 * Restart relaunches the executable and exits — used after ChangeDataRoot so the
 * new layout is picked up.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(731357291);
}

/**
 * TotalRAMMB is the machine's total physical memory in MiB — the upper bound for
 * the RAM slider. Returns 0 if the platform can't report it.
 */
export function TotalRAMMB(): $CancellablePromise<number> {
    return $Call.ByID(2148889837);
}
