// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ping returns the server status. A down or unreachable server yields
 * Status{Online:false} without an error — a normal state the UI renders, not a
 * failure. (ctx is accepted for the Wails binding; minequery uses its own timeout.)
 */
export function Ping(host: string, port: number): $CancellablePromise<$models.Status> {
    return $Call.ByID(1850944699, host, port).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
