// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3574173440);
}

/**
 * Launch runs the full chain: sync files -> issue session -> build command ->
 * start the JVM and stream its lifecycle as events.
 */
export function Launch(slug: string): $CancellablePromise<void> {
    return $Call.ByID(4211135650, slug);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3928339033);
}
