// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Report {
    "ok": boolean;
    "statuses": Status[];

    /** Creates a new Report instance. */
    constructor($$source: Partial<Report> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("statuses" in $$source)) {
            this["statuses"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     */
    static createFrom($$source: any = {}): Report {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("statuses" in $$parsedSource) {
            $$parsedSource["statuses"] = $$createField1_0($$parsedSource["statuses"]);
        }
        return new Report($$parsedSource as Partial<Report>);
    }
}

export class Status {
    "name": string;
    "ok": boolean;

    /**
     * State is a machine-readable detail: "operational", "maintenance", "off",
     * "unreachable" or "error". The UI branches on it.
     */
    "state": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = Status.createFrom;
const $$createType1 = $Create.Array($$createType0);
