// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info is the UI-facing result of an update check. When NeedsUpdate is false the
 * release fields are empty.
 */
export class Info {
    "current": string;
    "needsUpdate": boolean;
    "latest": string;
    "downloadURL": string;
    "checksum": string;
    "fileSize": number;
    "changelog": string[];
    "isMandatory": boolean;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("needsUpdate" in $$source)) {
            this["needsUpdate"] = false;
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("downloadURL" in $$source)) {
            this["downloadURL"] = "";
        }
        if (!("checksum" in $$source)) {
            this["checksum"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("changelog" in $$source)) {
            this["changelog"] = [];
        }
        if (!("isMandatory" in $$source)) {
            this["isMandatory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changelog" in $$parsedSource) {
            $$parsedSource["changelog"] = $$createField6_0($$parsedSource["changelog"]);
        }
        return new Info($$parsedSource as Partial<Info>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
