// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply re-checks for an update, downloads it (emitting update:progress), verifies
 * its SHA256 and atomically replaces the running binary. It does NOT restart —
 * call Restart after a successful Apply. The check is re-run here so the download
 * URL and checksum are server-authoritative, not passed from the UI.
 */
export function Apply(): $CancellablePromise<void> {
    return $Call.ByID(3959036244);
}

/**
 * Check asks GET /v1/launcher/update?platform=&version= whether a newer release
 * is available. The server decides needs_update; we just relay it.
 */
export function Check(): $CancellablePromise<$models.Info> {
    return $Call.ByID(3994704536).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Restart launches the (now replaced) executable and exits the current process.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(2701098827);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1319994540);
}

// Private type creation functions
const $$createType0 = $models.Info.createFrom;
