// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GameSession is what the launcher passes to the game's auth arguments. Its
 * AccessToken is the game token (a short opaque string), NOT the launcher JWT.
 */
export class GameSession {
    "uuid": string;
    "username": string;
    "accessToken": string;

    /** Creates a new GameSession instance. */
    constructor($$source: Partial<GameSession> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("accessToken" in $$source)) {
            this["accessToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameSession instance from a string or object.
     */
    static createFrom($$source: any = {}): GameSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameSession($$parsedSource as Partial<GameSession>);
    }
}

export class User {
    "uuid": string;
    "username": string;
    "avatarUrl": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("avatarUrl" in $$source)) {
            this["avatarUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}
