// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CurrentUser(): $CancellablePromise<$models.User> {
    return $Call.ByID(3694664825).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GameSession issues a fresh game session for launching: it first ensures the
 * launcher JWT is valid (refreshing if stale), then exchanges it for a new game
 * token. The game token is never cached — a new one each launch.
 */
export function GameSession(): $CancellablePromise<$models.GameSession> {
    return $Call.ByID(4247097229).then(($result: any) => {
        return $$createType1($result);
    });
}

export function IsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(3395470652);
}

export function Login(username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3054638606, username, password);
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(719426095);
}

/**
 * Restore re-establishes a session from a stored refresh token (startup path).
 * Returns false (no error) when there is nothing stored to restore.
 */
export function Restore(): $CancellablePromise<boolean> {
    return $Call.ByID(2859097117);
}

// Private type creation functions
const $$createType0 = $models.User.createFrom;
const $$createType1 = $models.GameSession.createFrom;
