// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * OptionalFile is the UI-facing view of an optional component: presentation
 * metadata from the manifest plus the total size of its files.
 */
export class OptionalFile {
    "id": string;
    "name": string;
    "desc": string;
    "sizeBytes": number;
    "defaultOn": boolean;

    /** Creates a new OptionalFile instance. */
    constructor($$source: Partial<OptionalFile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("defaultOn" in $$source)) {
            this["defaultOn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OptionalFile instance from a string or object.
     */
    static createFrom($$source: any = {}): OptionalFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OptionalFile($$parsedSource as Partial<OptionalFile>);
    }
}

export class Profile {
    "slug": string;
    "title": string;
    "version": string;
    "mcVersion": string;
    "desc": string;

    /**
     * Presentation fields, authored in index.json on S3 (not computed):
     */
    "icon": string;
    "accent": string;
    "accentDim": string;
    "bg": string;
    "order": number;
    "hidden": boolean;
    "servers": Server[];
    "manifestPath": string;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("mcVersion" in $$source)) {
            this["mcVersion"] = "";
        }
        if (!("desc" in $$source)) {
            this["desc"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("accentDim" in $$source)) {
            this["accentDim"] = "";
        }
        if (!("bg" in $$source)) {
            this["bg"] = "";
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }
        if (!("hidden" in $$source)) {
            this["hidden"] = false;
        }
        if (!("servers" in $$source)) {
            this["servers"] = [];
        }
        if (!("manifestPath" in $$source)) {
            this["manifestPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField11_0($$parsedSource["servers"]);
        }
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

export class Server {
    "name": string;
    "host": string;
    "port": number;

    /** Creates a new Server instance. */
    constructor($$source: Partial<Server> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     */
    static createFrom($$source: any = {}): Server {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Server($$parsedSource as Partial<Server>);
    }
}

// Private type creation functions
const $$createType0 = Server.createFrom;
const $$createType1 = $Create.Array($$createType0);
