// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Fetcher(): $CancellablePromise<engine$0.Fetcher> {
    return $Call.ByID(2661520779);
}

/**
 * Manifest searches the full index (including hidden profiles) so a hidden but
 * still-launchable profile resolves.
 */
export function Manifest(slug: string): $CancellablePromise<engine$0.Manifest> {
    return $Call.ByID(2046852417, slug).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OptionalFiles returns the optional components of a profile for the toggles UI,
 * summing each id's file sizes.
 */
export function OptionalFiles(slug: string): $CancellablePromise<$models.OptionalFile[]> {
    return $Call.ByID(3978125991, slug).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Profiles returns visible profiles sorted by Order — for the UI list.
 */
export function Profiles(): $CancellablePromise<$models.Profile[]> {
    return $Call.ByID(2989613254).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = engine$0.Manifest.createFrom;
const $$createType1 = $models.OptionalFile.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Profile.createFrom;
const $$createType4 = $Create.Array($$createType3);
