// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export type Fetcher = any;

export class Manifest {
    "files": ManifestFile[];
    "strictDirs": string[];
    "runtime": string;
    "recommendedRamMB": number;
    "minRamMB": number;

    /** Creates a new Manifest instance. */
    constructor($$source: Partial<Manifest> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("strictDirs" in $$source)) {
            this["strictDirs"] = [];
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = "";
        }
        if (!("recommendedRamMB" in $$source)) {
            this["recommendedRamMB"] = 0;
        }
        if (!("minRamMB" in $$source)) {
            this["minRamMB"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     */
    static createFrom($$source: any = {}): Manifest {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        if ("strictDirs" in $$parsedSource) {
            $$parsedSource["strictDirs"] = $$createField1_0($$parsedSource["strictDirs"]);
        }
        return new Manifest($$parsedSource as Partial<Manifest>);
    }
}

export class ManifestFile {
    "path": string;
    "sha256": string;
    "size": number;
    "optional": boolean;

    /**
     * ID identifies an optional file so config.enabledOptional can reference it
     * (e.g. "optifine"). Empty for required files.
     */
    "id"?: string;

    /** Creates a new ManifestFile instance. */
    constructor($$source: Partial<ManifestFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("optional" in $$source)) {
            this["optional"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManifestFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ManifestFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ManifestFile($$parsedSource as Partial<ManifestFile>);
    }
}

// Private type creation functions
const $$createType0 = ManifestFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
